apiVersion: v1
kind: Service
metadata:
  name: backend-nodeport-code
spec:
  type: NodePort
  selector:
    app: code-processing-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30002 # Specify the desired node port number here
