apiVersion: v1
kind: Service
metadata:
  name: backend-nodeport-mcqandsaq
spec:
  type: NodePort
  selector:
    app: mcq-structured-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30001 # Specify the desired node port number here
